### ISSUE TITLE
[Windows] Please, configure correctly your ghdl path

### ISSUE THREAD

**Issue by edsonms** [TerosTechnology/terosHDL#51]
Hi,

When trying to Run my test I get a yellow notification message saying:
![image](https://user-images.githubusercontent.com/27818470/79673457-46c89880-81b0-11ea-97b9-66ca670b1cce.png)

How do I config my GHDL path? I already have added it to environment variables.

Kind Regards

**Comment by edsonms** [comment]
I have set it here:
![image](https://user-images.githubusercontent.com/27818470/79673625-bd19ca80-81b1-11ea-9c48-1adc5ddbb71f.png)
But I keep getting the same message

**Comment by qarlosalberto** [comment]
Maybe it's a problem with the white spaces in the path. Try to change ' '
by '\ '

**Comment by smgl9** [comment]
Hi @edsonms  

You are not the first reporting exactly the same issue. We will take a look as soon as possible and  let you know.

**Comment by edsonms** [comment]
After update to version 1.1.7 the issue was solved.

**Comment by smgl9** [comment]
I'm glad to hear that :)

**Comment by edsonms** [comment]
Although now I got stuck in the following:
![image](https://user-images.githubusercontent.com/27818470/79696725-d45dc400-8254-11ea-9ef2-7f35b4a2fea3.png)

**Comment by edsonms** [comment]
I also get the following error message when I try to select a Test:
![image](https://user-images.githubusercontent.com/27818470/79696768-0cfd9d80-8255-11ea-8604-175d242e1d59.png)

**Comment by smgl9** [comment]
ok, 
Mind that you have a button on the toolbar to switch btween simulators, push the button as many times as needed to ensure that you have selected ghdl.

![image](https://user-images.githubusercontent.com/34767708/79696834-595dd300-827f-11ea-9a3a-2921fd94f24a.png)

**Comment by edsonms** [comment]
> ok,
> Mind that you have a button on the toolbar to switch btween simulators, push the button as many times as needed to ensure that you have selected ghdl.
> 
> ![image](https://user-images.githubusercontent.com/34767708/79696834-595dd300-827f-11ea-9a3a-2921fd94f24a.png)

Hi, it is already selected the GHDL simulator. And the path problem does not happen anymore

**Comment by edsonms** [comment]
Solved the problem. Apparently, it was some problem with the path I was using (virtual machine). 

In summary, updating to version 1.1.7 solved the issue original problem
